# Generated by Django 6.0.3 on 2026-03-25 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('relevant', 'Relevant'), ('irrelevant', 'Irrelevant')], default='pending', max_length=20)),
                ('suppressed_at_content_version', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='content.contentitem')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='keywords.keyword')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'unique_together': {('keyword', 'content_item')},
            },
        ),
    ]
